config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: '/',
             path_names: { sign_in: 'login', sign_out: 'logout' }
  devise_for :providers,
             controllers: { registrations: 'providers_registrations' },
             path_names: { sign_up: 'register' }
  devise_for :administrators

  resources :administrators, :calendar_events, :appointments, :availabilities

  resources :providers do
    member do
      get 'home'
      get 'calendar'
    end
    resources :calendar_events
    resources :appointments
    resources :availabilities
  end

  ActiveAdmin.routes(self)

  root 'welcome#index'

end

app/models/provider.rb
class Provider < User
  validates :name, :email, :phone, :zip_code, presence: true

  belongs_to :specialty

  after_initialize :set_defaults, if: :new_record?

  private

  def set_defaults
    self.is_active = false
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy, :calendar]

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
        format.json { render :show, status: :created, location: @provider }
      else
        format.html { render :new }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  def update
    if @provider.update(provider_params)
      redirect_to edit_provider_path(@provider), notice: 'Your account was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url, notice: 'Provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /providers/1/home
  def home
  end

  # GET /providers/1/calendar
  def calendar
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_provider
    @provider = Provider.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def provider_params
    params.require(:provider).permit(:name, :email, :password, :password_confirmation, :zip_code, :phone, :specialty_id)
  end
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/providers/_form.html.erb
<%= simple_form_for(@provider) do |f| %>
  <%= f.input :name, placeholder: "Your full name.", label: false %>
  <%= f.input :email, placeholder: "Your email address.", label: false %>
  <%= f.input :zip_code, placeholder: "Zip code of your practice.", label: false %>
  <%= f.input :phone, placeholder: "Your phone number.", label: false %>
  <%= f.association :specialty, placeholder: "Choose your specialty.", label: false, :value_method => :id %>
  <%= f.button :submit, "Save" %>

<% end %>

app/views/providers/calendar.html.erb
<div id="calendar-tools">
  <%= link_to "Create Availability", new_provider_availability_path(current_user.id), :class => "button", :method => :get  %>
  <%= link_to "Create Appointment", new_provider_appointment_path(@provider.id), :class => "button", :method => :get  %>
</div>
<div id="calendar-container"> 
  <%= render 'calendar_events/calendar' %>
</div>

app/views/providers/edit.html.erb
<div id="account-info"> 

  <h3>Account Info</h3>

  <%= render 'form' %>

</div>

<div id="security">

  <h3>Security</h3>

  <a class="button">Logout</a>
  <a class="button">Change Password</a>

 </div>

app/views/providers/home.html.erb
<div class="flex-box flex-box-big">
  <h2>Upcoming Appointments</h2>
  <table class="table-minimal">
    <thead>
      <tr>
        <th>Date</th>
        <th>Patient</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Today at 10:00 am</td>
        <td><a href="javascript:void()">Danielle Steel</a></td>
        <td><button>Start</button>&nbsp;<button>Cancel</button></td>
      </tr>
      <tr>
        <td>Today at 6:00 pm</td>
        <td><a href="javascript:void()">Mark Twain</a></td>
        <td><button>Start</button>&nbsp;<button>Cancel</button></td>
      </tr>
      <tr>
        <td>Tomorrow at 12:00 pm</td>
        <td><a href="javascript:void()">John Updike</a></td>
        <td><button>Start</button>&nbsp;<button>Cancel</button></td>
      </tr>
      <tr>
        <td>Friday at 11:00 am</td>
        <td><a href="javascript:void()">Margaret Atwood</a></td>
        <td><button>Start</button>&nbsp;<button>Cancel</button></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/providers/index.html.erb
<h1>Listing providers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @providers.each do |provider| %>
      <tr>
        <td><%= link_to 'Show', provider %></td>
        <td><%= link_to 'Edit', edit_provider_path(provider) %></td>
        <td><%= link_to 'Destroy', provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Provider', new_provider_path %>

app/views/providers/new.html.erb
<h1>New provider</h1>

<%= render 'form' %>

<%= link_to 'Back', providers_path %>

app/views/providers/show.html.erb
<h1>Provider Profile</h1>

<ul>
  <li>Name: <%= @provider.name %></li>
  <li>ID: <%= @provider.id %></li>
  <li>Email: <%= @provider.email %></li>
</ul>