config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: '/',
             path_names: { sign_in: 'login', sign_out: 'logout' }
  devise_for :providers,
             controllers: { registrations: 'providers_registrations' },
             path_names: { sign_up: 'register' }
  devise_for :administrators

  resources :administrators, :calendar_events, :appointments, :availabilities

  resources :providers do
    member do
      get 'home'
      get 'calendar'
    end
    resources :calendar_events
    resources :appointments
    resources :availabilities
  end

  ActiveAdmin.routes(self)

  root 'welcome#index'

end

app/views/share/_navigation.html.erb
<%= render "share/primary_navigation" %>
<% if user_signed_in? %>
<%= render "share/secondary_navigation" %>
<% end %>

app/views/share/_primary_navigation.html.erb
<header class="primary-navigation">
  <div class="navigation-wrapper">
    <div class="logo"><%= link_to "Outpatient.", root_path %></div>
    <div class="navigation-tools">
    <% if user_signed_in? %>
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path %> or
      <%= link_to "Sign up", new_provider_registration_path %>
    <% end %>
    </div>
  </div>
</header>

app/views/share/_secondary_navigation.html.erb
<header class="secondary-navigation">
  <div class="navigation-wrapper">
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">
      <%= image_tag("menu-white.png") %>
    </a>
    <div class="nav">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <%= content_tag :li, link_to("Appointments", provider_appointments_path(current_user)), class: "nav-link #{css_class_active_for(provider_appointments_path(current_user))}" %>
        <%= content_tag :li, link_to("Calendar", calendar_provider_path(current_user)), class: "nav-link #{css_class_active_for(calendar_provider_path(current_user))}" %>
        <%= content_tag :li, link_to("My Account", edit_provider_path(current_user)), class: "nav-link #{css_class_active_for(edit_provider_path(current_user))}" %>
      </ul>
    </div>

  </div>
</header>