config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: '/',
             path_names: { sign_in: 'login', sign_out: 'logout' }
  devise_for :providers,
             controllers: { registrations: 'providers_registrations' },
             path_names: { sign_up: 'register' }
  devise_for :administrators

  resources :administrators, :calendar_events, :appointments, :availabilities

  resources :providers do
    member do
      get 'home'
      get 'calendar'
    end
    resources :calendar_events
    resources :appointments
    resources :availabilities
  end

  ActiveAdmin.routes(self)

  root 'welcome#index'

end

app/controllers/providers_registrations_controller.rb
class ProvidersRegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:name, :phone, :zip_code, :specialty_id)
  end
end

app/views/providers_registrations/_form.html.erb
<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= f.input :name, placeholder: "Your full name.", label: false %>
  <%= f.input :email, placeholder: "Your email address.", label: false %>
  <%= f.input :password, placeholder: "Password.", label: false %>
  <%= f.input :password_confirmation, placeholder: "Password confirmation.", label: false %>
  <%= f.input :zip_code, placeholder: "Zip code of your practice.", label: false %>
  <%= f.input :phone, placeholder: "Your phone number.", label: false %>
  <%= f.association :specialty, placeholder: "Choose your specialty.", label: false, :value_method => :id %>
  <%= f.button :submit, "Sign up" %>
<% end %>

app/views/providers_registrations/new.html.erb
<div class="solo-form">

  <h2>Sign up</h2>

  <%= render 'form' %>

</div>